/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.rev.thriftentity;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.13.0)", date = "2019-12-22")
public enum CharacterType implements org.apache.thrift.TEnum {
  CHARACTER_TYPE_1(0),
  CHARACTER_TYPE_2(1),
  CHARACTER_TYPE_3(2),
  CHARACTER_TYPE_4(3),
  CHARACTER_TYPE_5(4);

  private final int value;

  private CharacterType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static CharacterType findByValue(int value) { 
    switch (value) {
      case 0:
        return CHARACTER_TYPE_1;
      case 1:
        return CHARACTER_TYPE_2;
      case 2:
        return CHARACTER_TYPE_3;
      case 3:
        return CHARACTER_TYPE_4;
      case 4:
        return CHARACTER_TYPE_5;
      default:
        return null;
    }
  }
}
