/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.multiplayer.entitiesAndServices;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.12.0)", date = "2019-12-22")
public enum Specialization implements org.apache.thrift.TEnum {
  SPECIALIZATION_1(0),
  SPECIALIZATION_2(1),
  SPECIALIZATION_3(2),
  SPECIALIZATION_4(3),
  SPECIALIZATION_5(4);

  private final int value;

  private Specialization(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static Specialization findByValue(int value) { 
    switch (value) {
      case 0:
        return SPECIALIZATION_1;
      case 1:
        return SPECIALIZATION_2;
      case 2:
        return SPECIALIZATION_3;
      case 3:
        return SPECIALIZATION_4;
      case 4:
        return SPECIALIZATION_5;
      default:
        return null;
    }
  }
}
